/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToeflIbtRouteImport } from './routes/toefl-ibt'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as EssaiGratuitRouteImport } from './routes/essai-gratuit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursSlugRouteImport } from './routes/cours.$slug'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as ApiPublicShopifyOrderRouteImport } from './routes/api/public/shopify-order'

const ToeflIbtRoute = ToeflIbtRouteImport.update({
  id: '/toefl-ibt',
  path: '/toefl-ibt',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaiGratuitRoute = EssaiGratuitRouteImport.update({
  id: '/essai-gratuit',
  path: '/essai-gratuit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursSlugRoute = CoursSlugRouteImport.update({
  id: '/cours/$slug',
  path: '/cours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicShopifyOrderRoute = ApiPublicShopifyOrderRouteImport.update({
  id: '/api/public/shopify-order',
  path: '/api/public/shopify-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/panier': typeof PanierRoute
  '/toefl-ibt': typeof ToeflIbtRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/api/public/shopify-order': typeof ApiPublicShopifyOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/panier': typeof PanierRoute
  '/toefl-ibt': typeof ToeflIbtRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/api/public/shopify-order': typeof ApiPublicShopifyOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/essai-gratuit': typeof EssaiGratuitRoute
  '/panier': typeof PanierRoute
  '/toefl-ibt': typeof ToeflIbtRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/api/public/shopify-order': typeof ApiPublicShopifyOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/catalogue'
    | '/checkout'
    | '/contact'
    | '/essai-gratuit'
    | '/panier'
    | '/toefl-ibt'
    | '/compte'
    | '/cours/$slug'
    | '/api/public/shopify-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/auth'
    | '/catalogue'
    | '/checkout'
    | '/contact'
    | '/essai-gratuit'
    | '/panier'
    | '/toefl-ibt'
    | '/compte'
    | '/cours/$slug'
    | '/api/public/shopify-order'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/auth'
    | '/catalogue'
    | '/checkout'
    | '/contact'
    | '/essai-gratuit'
    | '/panier'
    | '/toefl-ibt'
    | '/_authenticated/compte'
    | '/cours/$slug'
    | '/api/public/shopify-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AuthRoute: typeof AuthRoute
  CatalogueRoute: typeof CatalogueRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  EssaiGratuitRoute: typeof EssaiGratuitRoute
  PanierRoute: typeof PanierRoute
  ToeflIbtRoute: typeof ToeflIbtRoute
  CoursSlugRoute: typeof CoursSlugRoute
  ApiPublicShopifyOrderRoute: typeof ApiPublicShopifyOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toefl-ibt': {
      id: '/toefl-ibt'
      path: '/toefl-ibt'
      fullPath: '/toefl-ibt'
      preLoaderRoute: typeof ToeflIbtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essai-gratuit': {
      id: '/essai-gratuit'
      path: '/essai-gratuit'
      fullPath: '/essai-gratuit'
      preLoaderRoute: typeof EssaiGratuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$slug': {
      id: '/cours/$slug'
      path: '/cours/$slug'
      fullPath: '/cours/$slug'
      preLoaderRoute: typeof CoursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/shopify-order': {
      id: '/api/public/shopify-order'
      path: '/api/public/shopify-order'
      fullPath: '/api/public/shopify-order'
      preLoaderRoute: typeof ApiPublicShopifyOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AuthRoute: AuthRoute,
  CatalogueRoute: CatalogueRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  EssaiGratuitRoute: EssaiGratuitRoute,
  PanierRoute: PanierRoute,
  ToeflIbtRoute: ToeflIbtRoute,
  CoursSlugRoute: CoursSlugRoute,
  ApiPublicShopifyOrderRoute: ApiPublicShopifyOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
